[fullScreen.js] Deutsch Translation
daksh2k/Spicetify-stuff pull request #30
Opened 2022-11-14 10:53 UTC by SupLiCatinG

Adding deutsch translation for fullScreen.js

2022-11-14 12:41 UTC, SIMULATAN requested changes
Must've been a load of work :sweat_smile: 
Just looked through it and added some comments on things that stood out to me.

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +            fullscreenConfig: "Vollbildmodus konfiguration",
I'd instead use "Einstellungen des Vollbildmodis" or something like that, "Konfiguration" is a noun, and thus has to be capitalized

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +                setting: "Liedtext Ausrichtung",
maybe "Ausrichtung des Liedtextes"?

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +            playerControls: "Wiedegergabe steuerung",
again, "Steuerung" is a noun, in this case, I'd join the two words together

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +            trimTitle: "Trimmen Titel",
"Titel trimmen" / "Titel zuschneiden"

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +                always: "Jemand",
"Immer"

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +                date: "Veröffentlichungsdatum anzeigen",
"Immer + Veröffentlichungsdatum"

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +            upnextDisplay: "Nächste-titel Anzeige",
"Nächster Titel-Anzeige"
feel free to improve, my translation here is rather bad

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +                always: "Jemand",
"Immer"

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +                setting: "Anzeige der Lautstärkeleiste",
"Anzeige der Lautstärke" / "Lautstärkenleiste"

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +            appearanceSubHeader: "Achtung! Ändern Sie nur, wenn Sie wissen, was Sie tun!",
"... Ändern Sie **diese Einstellungen** nur, wenn ..."

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +                setting: "Upnächste Scroll-Animation",
"Nächstes Lied Scroll-Animation" or something like that maybe

2022-11-14 12:41 UTC, SIMULATAN commented on Extensions/fullScreen.js
> +            upnextTime: "Upnächste Zeit zu zeigen ",
`"nächster Titel" Anzeigedauer`

2022-11-15 09:50 UTC, daksh2k commented
Thanks @SupLiCatinG and @SIMULATAN for the translations,
Can you make the changes requested in this pull request, or are you opening another?

2022-11-15 09:56 UTC, closed without merging

2022-11-15 09:56 UTC, SupLiCatinG commented
I applied changes to new pull request.